package com.globi.infa.generator;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
public enum InfagenDefaults {
	
	DEFAULT_FIELD_LEVEL(Constants.DEFAULT_FIELD_LEVEL),
	DEFAULT_DESCRIPTION(Constants.DEFAULT_DESCRIPTION),
	DEFAULT_FOLDER_PERMISSION(Constants.DEFAULT_FOLDER_PERMISSION),
	DEFAULT_VERSION(Constants.DEFAULT_VERSION);

    @Getter
    private final String value;

    private static class Constants {
        public static final String DEFAULT_FIELD_LEVEL = "0";
        public static final String DEFAULT_DESCRIPTION = "Globi Autogenerated object. Kindly refrain from modifying it directly";
        public static final String DEFAULT_FOLDER_PERMISSION = "rwx---r--";
        public static final String DEFAULT_VERSION = "1";
        
        
    }
    
    @Override
    public String toString() {
        return this.value;
     }
}